io:
  star_path: path/to/particles.star
  data_path: path/to/particle_stack_dir
  ref_volume_path: path/to/reference_volume.mrc

data:
  batch_size: 1
  num_workers: 4
  particle_diameter: 200

modules:
  volume:
    num_volumes: 1